### ISSUE TITLE
Why pdf.close must be called explicitly and not via a destructor ? 

### ISSUE THREAD

**Issue by bashirmindee** [pypdfium2-team/pypdfium2#116]
It is really annoying to keep opening and closing the PDF. Can't we put the close method in the destructor of class class named PdfPage ?

**Comment by mara004** [comment]
I'm afraid we can't do this because the different close methods need to be called in correct order, which can't be guaranteed with destructor methods. Using `__del__()` is discouraged in general.[^1] Other libraries like pikepdf or pillow also provide `close()` instead.

There might be a `weakref` trick which Mike Kroutikov of pdfbrain is currently investigating, but I'm not convinced that this is a good idea.

[^1]: https://stackoverflow.com/questions/1481488/what-is-the-del-method-and-how-do-i-call-it#1481512

**Comment by mara004** [comment]
What @mkroutikov did with weakref doesn't work, I think (see https://github.com/innodatalabs/pdfbrain/issues/6). 

However, actually, I think this should be possible anyway. We just need to keep references to parent objects (and their respective parents) and ensure none of them has been closed yet before closing the child object.

However, closing of child objects might then be skipped if parents and children are garbage collected in the same cycle.
I need to verify if closing the parent also frees the memory of the kids - if so, this is not a problem. Otherwise, we might be able to keep track of released child objects via a list of weak references and close them first, even if Python attempts to finalise parent before child...

**Comment by mara004** [comment]
While testing, I made some confusing observations:
* Python frequently attempts to finalise kids after parents, not just at shutdown
* When commenting out the code that prohibits closing kids after parents (and the manual close calls), there are still no segmentation faults ... ?

Need to test more extensively. Perhaps something has changed in PDFium.
Anyway, I believe the current state can't do any harm and is certainly better than before.

**Comment by mara004** [comment]
Hmm, I did some testing and am still confused, but I think the addition in its current form at least can't do any harm.

**Comment by mara004** [comment]
Actually, I had to revert this again because - despite the order checking - this *does* still trigger random segfaults on exit, see https://github.com/pypdfium2-team/pypdfium2/commit/ee3222a51041e161e5d29488b3cb82cf62de1b50

**Comment by mara004** [comment]
I think I finally found a working way with weakref, see https://github.com/innodatalabs/pdfbrain/issues/6#issuecomment-1268955120.
I've started a branch: [`autoclose_via_weakref`](https://github.com/pypdfium2-team/pypdfium2/compare/autoclose_via_weakref).
