### ISSUE TITLE
Add python pathlib support for any file path operations

### ISSUE THREAD

**Issue by adam-huganir** [pypdfium2-team/pypdfium2#124]
Lowest priority since it's not going to prevent anyone from using the lib, but with how `pathlib.Path` has become usable everywhere in the standard library now, and is super handy, it would be nice to support.

e.g.
```python
doc = pdfium.FPDF_LoadDocument(test_pdf, None)
```
```
ArgumentError                             Traceback (most recent call last)
Input In [32], in <cell line: 1>()
----> 1 doc = pdfium.FPDF_LoadDocument(test_pdf, None)

ArgumentError: argument 1: <class 'TypeError'>: object of type 'PosixPath' has no len()
```

I can take care of this, I have been meaning to do some more open source work but haven't had the time, so I might create some more small tickets to knock out.

**Comment by mara004** [comment]
Thanks for your report. Improving compatibility with `pathlib` definitely is something to consider.
I don't think we can do anything about `FPDF_LoadDocument()` or other raw functions from the bindings file created by ctypesgen. It might be possible when constructing a `PdfDocument` support model object, but last time I checked I wanted to avoid importing `pathlib` in non-setup source code, to retain compatibility with older versions of Python.
Perhaps a conditional import or a well-placed cast to string could do the trick, though. Otherwise I think I could also be convinced to drop support for EOL Pythons at some point.

**Comment by mara004** [comment]
Done in the `devel` branch, but it will yet take some time until it can be merged.
Migrating setup code to pathlib is a different task and lower priority, but I might also do that at some point.
