### ISSUE TITLE
Support for PIL.PPMImage Plugin

### ISSUE THREAD

**Issue by rushabh-wadkar** [pypdfium2-team/pypdfium2#146]
pil_image = page.render_topil(scale=200/72)

The above render_topil returns PIL.Image.Image which in turn consumes high memory. Is it possible to render to PIL.PPMImage or custom PIL plugins ? https://pillow.readthedocs.io/en/stable/_modules/PIL/PpmImagePlugin.html

**Comment by mara004** [comment]
Well, since version 3, you can plug in any custom converter by subclassing [`BitmapConvBase`](https://pypdfium2.readthedocs.io/en/stable/python_api.html#pypdfium2._helpers.converters.BitmapConvBase) and passing it to
[`PdfPage.render_to()`](https://pypdfium2.readthedocs.io/en/stable/python_api.html#pypdfium2._helpers.page.PdfPage.render_to) or [`PdfDocument.render_to()`](https://pypdfium2.readthedocs.io/en/stable/python_api.html#pypdfium2._helpers.document.PdfDocument.render_to).

However, I am under the impression that `PpmImagePlugin` is just an opener/decoder and not a standalone class.
That said, you could save the image to a buffer (or temporary file) in a compressed format and then re-open it with PIL.

**Comment by mara004** [comment]
I take it this is still related to https://github.com/pypdfium2-team/pypdfium2/issues/141?

**Comment by mara004** [comment]
I think, for what you want to do, you don't even need a custom converter.
You could just save the image with PIL and reopen it, as I said:
```python
import io
import PIL.Image

# assuming raw_image is the uncompressed image obtained via `render_topil()`
buf = io.BytesIO()
raw_image.save(buf, format="ppm")
raw_image.close()
compressed_image = PIL.Image.open(buf)
# ...
buf.close()  # once finished with compressed_image
```
However, I doubt if that provides any advantage at all because the raw image still has to be in memory for some time in any case.
