### ISSUE TITLE
render_topil

### ISSUE THREAD

**Issue by dweingarden** [pypdfium2-team/pypdfium2#195]
I use the python code below to render a pdf page by page and then get the extents so I can zoom to the best width.  It worked in pypdfium2 version 3.20  but in 4.0 and above it says the page object has no attribute render_topil.  has this been superceeded?  Is there a better way to do this?  Thank you in advance

        pdf = pdfium.PdfDocument(file)
        pdf_npages = len(pdf)
        #render all pages to find the extents
        for pdf_page_number in range(pdf_npages):
            page = pdf.get_page(pdf_page_number)
#this is the problem function
            pil_image = page.render_topil(
                                          scale=1,
                                          rotation=0,
                                          crop=(0,0,0,0),
                                          greyscale=False,
                                          optimise_mode=pdfium.OptimiseMode.NONE,
                                          )

            pdf_images.append(pil_image)
            w, h = pil_image.size

**Comment by mara004** [comment]
Yes this was changed. Now it would be `page.render(...).to_pil()`.
But it'd be better if you were using the multi-page renderer which is parallelized and thus a magnitude faster.
```python
renderer = pdf.render(pdfium.PdfBitmap.to_pil, ...)
for pil_image in renderer:
    # ...
```
Also `optimise_mode` was renamed to `optimize_mode` and was changed to take None / str.

Taking a look at the updated documentation never harms and might have prevented you from bothering a busy (and sick) developer.

**Comment by mara004** [comment]
Also note that stacking rendered images in a list can skyrocket memory consumption for a long pdf and/or high scale.
I notice that many embedders seem to be overlooking this.

In a lot of cases, this is easily avoidable by using a generator and doing all work in a single loop.
If you actually have to keep multiple pages in memory simultaneously, you might want to add some measure to control memory consumption, i. e. a smarter cache. But it depends on the use case if that is necessary.

**Comment by mara004** [comment]
Previous discussions on this: e. g. #141, #146, https://github.com/mindee/doctr/discussions/1000

**Comment by mara004** [comment]
Only in the multipage renderer. I had to block that because of https://github.com/pypdfium2-team/pypdfium2/issues/164. Sadly, I was unable to find the cause.

Note that rendering in parallel with byte streams probably never worked reliably, so even in versions where it was not explicitly blocked it's definitely not advisable to do.

**Comment by mara004** [comment]
And rendering in parallel with a document opened from bytes was never advisable because of the much higher memory load (byte buffers not affected, though).

**Comment by mara004** [comment]
As this thread contains some potentially valuable information for other embedders, I decided to pin this issue under a new name.

**Comment by mara004** [comment]
Update: After a hint from doctr and some actual benchmarking, we surprisingly got to the conclusion that the process pool based renderer seems to provide no performance advantage while only consuming more memory and having serious problems with non-path input types.

The provisional plan is to change `PdfDocument.render()` to linear rendering. Process pool rendering might be moved into the CLI and retained on a opt-in basis for testing purposes (NOT recommended for users).

We apologize for having misled embedders in this regard and having made unverified claims that turned out to be wrong, but this came as a real surprise to us.

The next release will probably become a major release due to the removal of process pool related arguments.
On this occasion we will also merge in some longer-standing changes to the outline API.

**Comment by mara004** [comment]
Wait, though. Turns out this is more complicated.

I think the important bottleneck here is the fairly expensive `pil_image.save()` call being in the main process, not in worker jobs. This means the process pool queues up results in memory while the main process may lack far behind, which explains at least some of the bad effects.

If we fix this parallelization should still be an advantage for our CLI, at least with CPU-consuming encoders (e.g. png).
The key is that expensive bitmap processing code of callers need to be part of parallel jobs to avoid a level of queue growth which defies the generator advantage.

However, this still casts doubts on our current API - even though we can run caller code in jobs with converter/callback, it looks like process pools should better be outsourced to callers to avoid the above pitfall and get a cleaner code model.

Note to self: want to check if parallelization of rendering alone (without any post-processing) is any advantage.

**Comment by mara004** [comment]
Commit ae94f03 tries to address some of the above.

**Comment by mara004** [comment]
> Only in the multipage renderer. I had to block that because of https://github.com/pypdfium2-team/pypdfium2/issues/164. Sadly, I was unable to find the cause.

I think I have now found the cause, see 1a40d2f.

Making some progress on supporting bytes input via shared memory, too. But I'm not sure if there's any real advantage compared to a tempfile (creating shared memory seems to be fairly expensive).
