### ISSUE TITLE
Unexpected behavior: get_rect() requires count_rects()

### ISSUE THREAD

**Issue by guyrosin** [pypdfium2-team/pypdfium2#207]
Hi,
It seems `get_rect()` returns the actual rectangle only if `count_rects()` was previously executed on the same PdfTextPage object.

Here's a code example to reproduce:
```python
import urllib.request

import pypdfium2 as pdfium

pdf_path = "test.pdf"
urllib.request.urlretrieve(
    "https://www.africau.edu/images/default/sample.pdf", pdf_path
)
doc = pdfium.PdfDocument(pdf_path)
page = doc[0]
text_page = page.get_textpage()
print(text_page.get_rect(0))
print("----------")
text_page = page.get_textpage()
print(text_page.count_rects())
print(text_page.get_rect(0))

```

Output:
```
(0.0, 0.0, 0.0, 0.0)
----------
10
(57.375, 716.9340209960938, 292.9229736328125, 741.93603515625)
```

**Comment by mara004** [comment]
Thanks for reporting this!

PDFium docs say
```
// Function: FPDFText_CountRects
//          Counts number of rectangular areas occupied by a segment of text,
//          and caches the result for subsequent FPDFText_GetRect() calls.
```
so presumably this is known (deliberate) requirement of pdfium that FPDFText_CountRects() always needs to be called once before FPDFText_GetRect() (as should virtually always be the case in real-world code, anyway).
However, I agree the python support model should somehow handle this.

Apart from that, `get_rect()` also lacks a return code check. A failed `get_rect()` call should raise an exception rather than returning an all-zero rect.

**Comment by guyrosin** [comment]
Yeah, I agree (and must say it's a weird design choice...)
Thanks for the quick response!

**Comment by mara004** [comment]
> and must say it's a weird design choice...

Hmm, yeah, I guess GetRect() needs to know rect count for an OOB check of the caller's index (as this is C), but then one would think GetRect() could call CountRects() internally if no value was assigned to the cache yet.

**Comment by guyrosin** [comment]
Exactly!

**Comment by guyrosin** [comment]
OK, that makes sense. An exception along with a note in get_rect()'s documentation will probably suffice :)

**Comment by guyrosin** [comment]
Oh :/ yeah that makes it sounds like a mistake rather than just weird

**Comment by mara004** [comment]
anyway, thanks a lot for reporting this
