### ISSUE TITLE
package name missing in pip

### ISSUE THREAD

**Issue by nialldeacon** [pypdfium2-team/pypdfium2#231]
Hi folks,
I'm trying to install on CentOS linux and have hit a problem. When installing from pip (pip 20.3) using the `python3 -m pip install py` the package name appears to be missing. Hence it tries

`Building wheels for collected packages: unknown, unknown
  Running setup.py bdist_wheel for unknown ... done`

And then hits an issue being unable to find run the tokeniser

`  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/opt/rh/rh-python36/root/lib64/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-fsy206do/unknown/setup.py'
  
  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown`

I've tried building by downloading the tarball, editing the name by hand to setup.cfg, and installing via pip locally. This install process finishes but I can't import the package in python and the package doesn't appear in my site packages folder.

**Comment by mara004** [comment]
Although I'm the author of this project, I genuinely don't understand this error. I've never seen anything like this.

If applicable to your system, can you update pip, setuptools, packaging and wheel to the latest available versions and try again? I doubt if these packages still support EOL python 3.6, though - can you update to a newer python if necessary?

Also can you confirm you actually ran `python3 -m pip install pypdfium2` and not just `python3 -m pip install py` as shown above?

**Comment by mara004** [comment]
Apart from that, normally a wheel should be selected, not an sdist, so ideally setup code shouldn't have to run at all.
It may be that the glibc requirement is blocking this, see https://github.com/pypdfium2-team/pypdfium2/issues/203.

Can you share your system's glibc version to check this?
For v4 it's quite high (2.26), though likely this is not necessary in practice yet.
You can attempt to re-tag with `wheel`'s new CLI, or first try with pypdfium2 v3 which only requires 2.17.

**Comment by nialldeacon** [comment]
Thanks for getting back to me. Apologies on the typo in the original post, I was trying `python3 -m pip install pypdfium2`

My glibc is 2.17 and pypdfium2 v3.21.1 installed fine. With a bit of reading through the previous README I got it doing the things I needed.

Thanks for your help.

On the mysterious setup.cfg file. When I originally ran pip it downloaded from 
https://files.pythonhosted.org/packages/db/d6/4a5aee6ff4632a8bdfb29d1a1d805f62a6b7a9a53a888fdd0e4a2c32d097/pypdfium2-4.16.0.tar.gz
I just ran wget on this tarball, extracted it and the setup.cfg file was there in the main directory.

**Comment by mara004** [comment]
Thank you, that shines some light on the problem. To sum up, I think there are two issues here:
* a) v4 wheels are tagged with a glibc requirement that is too high for your distro. Somewhat embarassingly, the tag is incorrectly high and the true requirement is still 2.17 though, see #203. I'm thinking about what I can do.
* b) v3 still had a live [`setup.cfg`](https://github.com/pypdfium2-team/pypdfium2/blob/3.21.1/setup.cfg) file. I believe your "unknown name" issue may be due to your setup package versions not supporting the newer `pyproject.toml` format yet.

If a) were the only problem you could get v4 by re-tagging wheels. However b) will be difficult since I do not wish to roll back to legacy setup.cfg.

> I just ran wget on this tarball, extracted it and the setup.cfg file was there in the main directory.

Ah, I see, thanks! Apparently setuptools automatically adds an effectively empty setup.cfg file if none was found.
