### ISSUE TITLE
Got different result of "pdfium_page.render()" on MacOS and Linux

### ISSUE THREAD

**Issue by zqkou** [pypdfium2-team/pypdfium2#304]
### Checklist

- [X] I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
- [X] I have read and acknowledged the [response policy](https://github.com/pypdfium2-team/pypdfium2#contributions).

### Description

I am using pdfplumber (which implemented based on pypdfium2) to render thumbnail image for PDF doc. And got different result on MacOS and Linux.

The original issue was reported at: https://github.com/jsvine/pdfplumber/issues/1115

I got answer from pdfplumber community, that `pdfplumber` delegates image generation to `pypdfium2`
https://github.com/jsvine/pdfplumber/blob/147f2c4c07dc1191fc1d05bb589b4f6af3aaf74a/pdfplumber/display.py#L59-L67
```python
    img: PIL.Image.Image = pdfium_page.render(
        # Modifiable arguments
        scale=resolution / 72,
        no_smoothtext=not antialias,
        no_smoothpath=not antialias,
        no_smoothimage=not antialias,
        # Non-modifiable arguments
        prefer_bgrx=True,
    ).to_pil()
```

Following are the supporting information for your reference.

Thanks a lot!

## PDF file
[page1~3.pdf](https://github.com/jsvine/pdfplumber/files/14597452/page1.3.pdf)

## Expected behavior

The image should be identical on both platforms.

## Actual behavior

Some text are missing from the thumbnail image got from Linux platform.

## Screenshots

From MacOS:
![image](https://github.com/jsvine/pdfplumber/assets/20944084/7c315557-1fe3-4167-ac22-9c08f3d0eee0)

From Linux:
![image](https://github.com/jsvine/pdfplumber/assets/20944084/5d167f11-b193-48c4-be77-65e2c47d9a1d)

### Install Info

On my MacOS machine (got correct result):
```shell
pypdfium2 4.27.0
pdfium 123.0.6281.0 at /opt/homebrew/anaconda3/envs/docmaster/lib/python3.10/site-packages/pypdfium2_raw/libpdfium.dylib
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
macOS-14.4-arm64-arm-64bit
Name: pypdfium2
Version: 4.27.0
Summary: Python bindings to PDFium
Home-page: https://github.com/pypdfium2-team/pypdfium2
Author: pypdfium2-team
Author-email: geisserml@gmail.com
License: (Apache-2.0 OR BSD-3-Clause) AND LicenseRef-PdfiumThirdParty
Location: /opt/homebrew/anaconda3/envs/docmaster/lib/python3.10/site-packages
Requires: 
Required-by: pdfplumber
```

On my Linux machine (got wrong result):
```
pypdfium2 4.28.0
pdfium 124.0.6337.0 at /usr/local/lib/python3.9/site-packages/pypdfium2_raw/libpdfium.so
Python 3.9.18 (main, Mar 12 2024, 12:39:30) 
[GCC 12.2.0]
Linux-4.18.0-372.52.1.el8_6.x86_64-x86_64-with-glibc2.36
Name: pypdfium2
Version: 4.28.0
Summary: Python bindings to PDFium
Home-page: https://github.com/pypdfium2-team/pypdfium2
Author: pypdfium2-team
Author-email: geisserml@gmail.com
License: (Apache-2.0 OR BSD-3-Clause) AND LicenseRef-PdfiumThirdParty
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: pdfplumber
```

### Validity

- [X] I confirm that I ran all commands, and pasted the whole output.

**Comment by mara004** [comment]
The screenshots are quite small and there doesn't seem to be a higher resolution, so I can't really compare.
But I think the issue is not reproducible with pdfium 6365 on my Fedora 37 device:  [page1 3_1](https://github.com/pypdfium2-team/pypdfium2/assets/65915611/b07a51b0-76c8-43aa-9cdf-4830aad63395)

Also note that you are using two different versions of pdfium/pypdfium2 on the two devices (see above install info).
To rule out a version-specific issue, please align installed versions.

If you ask me though, I believe this might be an issue with a missing system font on the Linux device.
Try to open the PDF with a font inspector (e.g. Okular -> PDF Properties -> Fonts) and see if all fonts are present or substituted with a reasonable choice. For me it is:
![image](https://github.com/pypdfium2-team/pypdfium2/assets/65915611/640e706c-dba2-4cd8-adbb-ec5991641d4c)
