### ISSUE TITLE
expose more details in PdfiumError 

### ISSUE THREAD

**Issue by elonzh** [pypdfium2-team/pypdfium2#308]
### Checklist

- [X] I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
- [X] I have read and acknowledged the [response policy](https://github.com/pypdfium2-team/pypdfium2#contributions).

### Description

For example `error_code` when available.

An common user case is pypdfium2 will raise `PdfiumError` when document is encrypted and we didn't provide a password.

> pypdfium2._helpers.misc.PdfiumError: Failed to load document (PDFium: Incorrect password error).

```python
...
    if pdfium_c.FPDF_GetPageCount(pdf) < 1:
        err_code = pdfium_c.FPDF_GetLastError()
        raise PdfiumError(f"Failed to load document (PDFium: {pdfium_i.ErrorToStr.get(err_code)}).")
...
```

Right now if we want to detect such exceptions, the only way is matching the error string which is inefficient and unstable.

---

### Prefer solution:

Add a enum class for `ErrorToStr` and expose a `error_code` in PdfiumError`.

### Install Info

```shell
pypdfium2 4.27.0
pdfium 123.0.6281.0
Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

### Validity

- [X] I confirm that I ran all commands, and pasted the whole output.

**Comment by mara004** [comment]
Good point. I agree matching against the error string is unfortunate.
TBH, I never really thought much about programmatic use of exceptions or handling of error subtypes.
However, I think I'd not add an enum, but just ask callers to check against the constants from the raw API (in this case, `FPDF_ERR_*`).

Do you have any more places other than document loading where this may be applicable?
Because most pdfium APIs are sort of limited to error or success (i.e. no distinction of specific errors), where there isn't really any further use for the return code.

**Comment by mara004** [comment]
Just found one more instance myself:
https://github.com/pypdfium2-team/pypdfium2/blob/66cfaa0c9113d10a939a112acac8ad7a79f2f4c3/src/pypdfium2/_helpers/document.py#L173-L178

I guess we should use the `exc_info` feature of logging here to provide a sort of "optional exception" that can be handled by the caller.

**Comment by elonzh** [comment]
> Do you have any more places other than document loading where this may be applicable?

No other error cases have been found yet for me.

**Comment by mara004** [comment]
Hmm, I think I might have misunderstood `exc_info` - seems like the exception is only logged, but not catchable.
I'm afraid that idea of an "optional exception" that can, but does not have to be caught, probably just doesn't exist. :(

But otherwise I think I've got an implementation ready for the devel branch.

**Comment by mara004** [comment]
I found sys.excepthook, which might be able to turn unhandled exceptions of a dedicated type into a logging message, but that doesn't sound very elegant, and maybe is not something we should use at library level.

**Comment by mara004** [comment]
Will become available when the v5 development work is finished.
