### ISSUE TITLE
How to increase DPI for rendering?

### ISSUE THREAD

**Issue by vikki3012** [pypdfium2-team/pypdfium2#98]
how can we increase the dpi of images?

**Comment by mara004** [comment]
pypdfium2 provides a `scale=` parameter for all PDF rendering helpers, such as `render_pdf_topil()`.
By default, 1/72 of an inch is rendered to 1x1 pixel, which may be scaled using a floating-point numer.
If you have the target resolution given as DPI, simply divide it by 72 and you will get the corresponding scale factor. Like this:

```python3
import pdfium

dpi = 300  # sample value
for image, num in pdfium.render_pdf_topil('in.pdf', scale=dpi/72):
    print(image, num)
```

It makes sense to handle resolution using a scale factor rather than DPI since resolution is defined by bitmap size, which is calculated using page dimensions and a scalar.
